version: 2.1

python-docker-image: &python-docker-image
  working_directory: ~/repo
  docker:
    - image: circleci/python:3.6
      environment:
        PIPENV_VENV_IN_PROJECT: true

commands:
  restore-pipenv-cache:
    description: "Restore pipenv cache"
    steps:
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

  save-pipenv-cache:
    description: "Save pipenv cache"
    steps:
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

jobs:
  test:
    <<: *python-docker-image
    steps:
      - checkout
      - restore-pipenv-cache
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save-pipenv-cache
      - run:
          name: Run tests
          command: pipenv run pytest
  lint:
    <<: *python-docker-image
    steps:
      - checkout
      - restore-pipenv-cache
      - run:
          name: Install dependencies
          command: pipenv sync --dev
      - save-pipenv-cache
      - run:
          name: Run linter
          command: pipenv run lint

  build-container:
    <<: *python-docker-image
    machine: true
    steps:
      - checkout
      - restore-pipenv-cache
      - run:
          name: Install dependencies
          command: pipenv sync
      - save-pipenv-cache
      - run: pipenv lock -r > requirements.txt
      - run:
          name: Build and push container
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t meandor/walter-white:$CIRCLE_SHA1 .
            docker tag meandor/walter-white:$CIRCLE_SHA1 meandor/walter-white:latest
            docker push meandor/walter-white:$CIRCLE_SHA1
            docker push meandor/walter-white:latest

workflows:
  build-test-deploy:
    jobs:
      - test
      - lint
      - build-container:
          - requires:
              - test
              - lint
