Parameters:
  ProjectName:
    Type: String
    Description: Name of the project this resources belongs to
  DatalakeStackName:
    Type: String
    Description: Stack name of the datalake

Resources:
  WalterWhiteServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Project
          Value: !Ref ProjectName
      AssumeRolePolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "batch.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
          ]
        }
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole"

  WalterWhiteRole:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: Project
          Value: !Ref ProjectName
      AssumeRolePolicyDocument:
        {
          "Version": "2012-10-17",
          "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
          ]
        }
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role"
      Policies:
        - PolicyName: write-to-datalake
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - Fn::ImportValue:
                      !Sub "${DatalakeStackName}-Arn"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - Fn::Join:
                      - ""
                      - - Fn::ImportValue:
                            !Sub "${DatalakeStackName}-Arn"
                        - "/*"

Outputs:
  ServiceRoleARN:
    Description: ARN of the ServiceRole
    Value: !GetAtt WalterWhiteServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-service-Arn'

  InstanceRoleARN:
    Description: ARN of the ServiceRole
    Value: !GetAtt WalterWhiteRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-instance-Arn'
