Parameters:
  ServiceName:
    Type: String
    Description: Name of the service
  BucketUri:
    Type: String
    Description: URI of the Datalake bucket
  MLFlowStackName:
    Type: String
    Description: The StackName of the MLFlow application

Resources:
  WalterWhiteJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: walter-white-training-JobDefinition
      Type: container
      ContainerProperties:
        Image: meandor/walter-white:latest
        Environment:
          - Name: DATALAKE
            Value: !Ref BucketUri
          - Name: LOGLEVEL
            Value: INFO
          - Name: MLFLOW_TRACKING_URI
            Value:
              Fn::ImportValue:
                !Join ['-', [!Ref 'MLFlowStackName', 'DNSRecord']]
        Vcpus: 16
        Memory: 28672
        Privileged: true
      RetryStrategy:
        Attempts: 1

Outputs:
  WatlerWhiteJobDefinitionArn:
    Description: ARN of WalterWhite JobDefinition
    Value: !Ref WalterWhiteJobDefinition
    Export:
      Name: !Sub '${AWS::StackName}-JobDefinition-Arn'
